data:
  raw_NQ: data/raw/NQ.csv
  clean_NQ: data/clean/NQ_clean.csv
  clean_ES: data/clean/ES_clean.csv
  clean_EMD: data/clean/EMD_clean.csv
  clean_YM: data/clean/YM_clean.csv
indicators: # setting the parameters used to compute the indexes
  rsi_period: 2
  hurst_window: 20
  short_composite_rsi: 2
  long_composite_rsi: 24
entry_thresholds: # setting the interval for RSI
  rsi_low: 10.0
  rsi_high: 20.0
  hurst_threshold: 0.5
exits: # setting the exit criteria
  max_time_exit: false
  max_time: 11
  take_profit: false
  max_profitable_closes: 5
  RSI_exit: false
  max_bars_in_trade: false
  composite_rsi_threshold: 0.5
ablation: # setting ablation boolean values to make testing and parameters isolation robust
  use_rsi: true
  use_hurst: true
  use_time_exit: true
  use_RSI_exit: true
  use_take_profit: true
transaction_costs: #Â modify if necessary
  commission_per_contract: 1.5
  slippage_tickets: 1
  point_value: 50
  tick_size: 0.25